name: Mayhem
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  look_mayhemfile: Mayhem/lookaheadparser.mayhemfile
  message_mayhemfile: Mayhem/messagereader.mayhemfile
  parseby_mayhemfile: Mayhem/parsebyparts.mayhemfile
  schema_mayhemfile: Mayhem/schemavalidator.mayhemfile
  serialize_mayhemfile: Mayhem/serialize.mayhemfile
  simpledom_mayhemfile: Mayhem/simpledom.mayhemfile
  simplepull_mayhemfile: Mayhem/simplepullreader.mayhemfile
  simplereader_mayhemfile: Mayhem/simplereader.mayhemfile
  simplewriter_mayhemfile: Mayhem/simplewriter.mayhemfile
  

jobs:
  build:
    name: ${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
      security-events: write
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Start analysis for lookaheadparser
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.look_mayhemfile}} --duration 300
          sarif-output: sarif

      - name: Start analysis for message
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.message_mayhemfile}} --duration 300
          sarif-output: sarif     
      
      - name: Start analysis for parsebyparts
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.parseby_mayhemfile}} --duration 300
          sarif-output: sarif   
      
      - name: Start analysis for schemavalidator
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.schema_mayhemfile}} --duration 300
          sarif-output: sarif

      - name: Start analysis for serialize
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.serialize_mayhemfile}} --duration 300
          sarif-output: sarif     
      
      - name: Start analysis for simpledom
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.simpledom_mayhemfile}} --duration 300
          sarif-output: sarif   
      
      - name: Start analysis for simplepullreader
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.simplepull_mayhemfile}} --duration 300
          sarif-output: sarif     
      
      - name: Start analysis for simplereader
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.simplereader_mayhemfile}} --duration 300
          sarif-output: sarif  
      
      - name: Start analysis for simplwriter
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.simplewriter_mayhemfile}} --duration 300
          sarif-output: sarif  

      - name: Upload SARIF file(s)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif
